### ISSUE TITLE
Change gamedir name

### ISSUE THREAD

**Issue by Velaron** [MoeMod/CSBTE-Mobile#13]
So you don't have to overwrite your vanilla game

**Comment by JusicP** [comment]
Possible names: cstrike_bte, csbte, bte_mobile.

**Comment by MoeMod** [comment]
It seems that no binary code is bound with gamedir.
Maybe it can be done by editing liblist.gam or some .cfg files.

**Comment by MoeMod** [comment]
I think that new resource archive can include only csbte,
without cstrike and valve, which can be downloaded on steam.
However a more convenient way is to read .nar files directly through an NAR-Filesystem...

**Comment by Velaron** [comment]
How do you build the .apk file? It is specified in the java code. BTW the .apk doesn't work on lot of devices. Try implementing this in your project, it's very easy. https://github.com/FWGS/mod-sample

**Comment by MoeMod** [comment]
working.
Gamedir will be changed to csbte, and it will be commited later.

**Comment by MoeMod** [comment]
In addition, this project needs to modify the original xash engine
because some features like CSO/CSNZ model loading should be implemented by a modified engine, and also a .apk not relying on the original one.
The .apk can be found at https://github.com/MoeMod/CSBTE-Mobile-Android

**Comment by MoeMod** [comment]
And I have removed google play services due to lack of it in most of Chinese-made devices, and I don't know whether it matters.

**Comment by MoeMod** [comment]
solved on v14.
