### ISSUE TITLE
CBaseEntity and its derived object's deconstructor never called

### ISSUE THREAD

**Issue by MoeMod** [MoeMod/CSBTE-Mobile#15]
ref in Chinese: https://tieba.baidu.com/p/5414873694

When we create an entity (by CREATY_NAMED_ENTITY, etc), the engine calls an "C"-export function in mp.dll whose name is the intended pev->classname. And that function calls new CAK47, etc, which will both alloc memory and call the constructor CAK47().
However, when we remove an entity (by RemoveEntity, FL_KILLME, etc), the engine will only free memory, without calling its deconstructor ~CAK47(). Then we some classes especially with STL members will cause memory-leak.

In order to avoid it, I have restricted any derived class from CBaseEntity should have trivially deconstructor aka std::is_trivially_destructible, so that it doesn't matter if deconstructor is never called.

However, it brings lots of inconvenience to coding. Maybe calling virtual ~CBaseEntity() in func OnFreeEntPrivateData() in cbase.cpp will help...

I am not quite good at C++, and need more discussions here, please.

**Comment by mittorn** [comment]
Is OnFreeEntPrivateData really called? It may be broken in xash3d. Add debug message to check it.
And maybe some macro in  cbase.h or cbase.cpp broken. It has msvc5 checks in half-life

**Comment by MoeMod** [comment]
maybe solved.
