### ISSUE TITLE
Radar not working

### ISSUE THREAD

**Issue by MoeMod** [MoeMod/CSBTE-Mobile#18]
Teammates' dots aren't drawn.

**Comment by hzd007** [comment]
New version bug feedback:
1. Bullet holes will be arranged neatly.
2, the details page can not be clicked.
3. Although the zombie's blood volume is weakened, the zombie can still move forward after being shot. Except for the 1,000-blood zombies, the other parent zombies are still very tough. The zombie's blood volume is thick and only slightly slowed down after being shot. The reserve bullets are few. It is difficult for human beings to defend them when attacking the zombies and buying bullets. position
4. Teammate's head name will show through the wall, the position of the enemy can be seen in the personal decisive battle, I hope you can delete it
5. Zombie mode can only buy CT weapons. There are few weapons to choose from. I hope the author can repair it as soon as possible.
6, the BOT of the Second Bureau of the Zombie mode will unify the same CT camp role, which will result in aesthetic fatigue for a long time.

**Comment by MoeMod** [comment]
solved.
