### ISSUE TITLE
zb1的一些问题

### ISSUE THREAD

**Issue by NOPEMS** [MoeMod/CSBTE-Mobile#7]
1.鼠标指着僵尸或者观察模式僵尸的HP百分比为4500％这样而不是100％
2.僵尸强度过高，bot太弱
3.太暗，无法调整亮度

**Comment by MoeMod** [comment]
translation
1. the hp display when observing or aiming at teammates should be percents 100% rather than value 4500%
2. zombies are too enhanced for bots to fight with them
3. lightstyle is too dark and cannot be adjusted

**Comment by MoeMod** [comment]
possible solution
1. TBD
2.change infection hp percent from 70% to 50% and -1000 hp for all zb
3. no need to change, cuz hm will be able to get nvg from supplybox in zb2 and that's what zb mode should be in early-2009

**Comment by MoeMod** [comment]
solved
